services:
  - name: theta-terminal-v3
    type: pserv
    runtime: docker
    plan: starter
    region: ohio
    branch: main
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - fromGroup: theta-terminal-envs
    healthCheckPath: /v3/terminal/mdds/status